### ISSUE TITLE
How do you move Forms with mouse?

### ISSUE THREAD

**Issue by ejamshidiasl** [csharpskolan/MonoGame.UI.Forms#1]
Hello
Where is code that moves Form with mouse?

**Comment by jni759** [comment]
Im not sure there is a simple way to do that now. The framework is quite
simple. There is alot of stuff to do..

Den 14 nov. 2018 09:28 skrev "Esmail Jamshidi Asl" <notifications@github.com
>:

Hello
Where is code that moves Form with mouse?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/csharpskolan/MonoGame.UI.Forms/issues/1>, or mute the
thread

**Comment by ejamshidiasl** [comment]
it has move ability now but i can't find code of move function.

**Comment by jni759** [comment]
Do you want events like "Move" and "Moved".



Den ons 14 nov. 2018 14:20 skrev Esmail Jamshidi Asl <
notifications@github.com>:

**Comment by ejamshidiasl** [comment]
i don't no!!!
now i can click on form and move it by mouse (drag&drop)
i want to see the code of  Forms drag&drop

**Comment by jni759** [comment]
https://github.com/csharpskolan/MonoGame.UI.Forms/blob/master/MonoGame.UI.Forms/ControlManager.cs

In method Update.

Den ons 14 nov. 2018 14:34 skrev Esmail Jamshidi Asl <
notifications@github.com>:

**Comment by ejamshidiasl** [comment]
YES, i need this code
thank you man

close #1
